export {default as BackTracking} from 'algorithm/pages/BackTracking'
export {default as BruteForce} from 'algorithm/pages/BruteForce'
export {default as DivideConquer} from 'algorithm/pages/DivideConquer'
export {default as Greedy} from 'algorithm/pages/Greedy'
export {default as DynamicProgramming} from 'algorithm/pages/DynamicProgramming'
